// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromotionService.Infrastructure.Persistence;

#nullable disable

namespace PromotionService.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    [Migration("20260315215151_AddPromotionCreatedByUserId")]
    partial class AddPromotionCreatedByUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromotionService.Domain.Entities.LoyaltyEventStreamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique();

                    b.ToTable("loyalty_event_stream", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.LoyaltySnapshotEntity", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AggregateId");

                    b.ToTable("loyalty_snapshots", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.PromotionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<Guid[]>("ProductIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<decimal?>("RequiredPoints")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("promotions", null, t =>
                        {
                            t.HasCheckConstraint("CK_promotions_date_range", "\"StartsAtUtc\" IS NULL OR \"EndsAtUtc\" IS NULL OR \"EndsAtUtc\" >= \"StartsAtUtc\"");

                            t.HasCheckConstraint("CK_promotions_discount_range", "\"DiscountPercentage\" > 0 AND \"DiscountPercentage\" <= 100");

                            t.HasCheckConstraint("CK_promotions_required_points", "\"Type\" <> 2 OR (\"RequiredPoints\" IS NOT NULL AND \"RequiredPoints\" > 0)");
                        });
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.UserPromotionProfileEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastOrderAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LoyaltyPoints")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OrdersCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("UserId");

                    b.ToTable("user_promotion_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_promotion_profiles_orders_nonnegative", "\"OrdersCount\" >= 0");

                            t.HasCheckConstraint("CK_user_promotion_profiles_points_nonnegative", "\"LoyaltyPoints\" >= 0");

                            t.HasCheckConstraint("CK_user_promotion_profiles_total_spent_nonnegative", "\"TotalSpent\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
