services:
  postgres:
    image: postgres:16
    container_name: promotionservice-postgres
    environment:
      POSTGRES_DB: promotion_service_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    networks:
      - promotionservice-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  promotionservice-api:
    container_name: promotionservice-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5293:8080"
    networks:
      - promotionservice-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__PostgreSql: Host=postgres;Port=5432;Database=promotion_service_dev;Username=postgres;Password=postgres
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  promotionservice-network:
